# A list of file extensions that nanoc will consider to be textual rather than
# binary. If an item with an extension not in this list is found,  the file
# will be considered as binary.
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss',  'xhtml', 'xml', 'coffee', 'slim','opf','nav' ]

# The path to the directory where all generated files will be written to. This
# can be an absolute path starting with a slash, but it can also be path
# relative to the site directory.
output_dir: epub3

meta_data:
  title: イチオシ商材カタログ
  author: KMR
  author_email: kmr@xxx.jp  # Default keywords to use when an item does not specify its own
  keywords: 'keyword1, keyword2'
  description: Undescribed website.
  copyright: "© copyright 2012 公益財団法人仙台市産業振興事業団."

base_url: http://domain.tld

